import {getPolicy, jinnTroopInRegion, removeGeneral, removeTroop, songTroopInCity} from "../auto/util";
import {getCityByID} from "./cities";
import {getRegionById} from "./regions";

export const jinnCards = [
    {
        id: 0,
        name: "",
        op: 0,
        country: "金",
        era: "None",
        removeAfterEvent: false,
        eventProperty: "",
        precondition: "",
        combat: false,
        effectText: "",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 1,
        name: "靖康之变",
        op: 4,
        country: "金",
        era: "None",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国未控制开封",
        combat: false,
        effectText: "宋国失去1国力。金国获得1国力，并提升1级内政等级。",
        unlock: "【金兵来了】【张邦昌还政】【赵榛】",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国未控制开封 效果：宋国失去1国力。金国获得1国力，并提升1级内政等级。 解锁：【金兵来了】【张邦昌还政】【赵榛】",
        pre: (G, ctx) => !G.song.cities.includes(21),
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("靖康之变")
            G.jinn.civil++;
        },
    },
    {
        id: 2,
        name: "折可求献三州",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国控制肤施",
        combat: false,
        effectText: "在陕西六路消灭2个部队，并结算路控制权。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国控制肤施 效果：在陕西六路消灭2个部队，并结算路控制权。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 3,
        name: "韩昉",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "提升金国1级内政等级或殖民能力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：提升金国1级内政等级或殖民能力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (arg === 'civil') G.jinn.civil++;
            if (arg === 'colonization') G.jinn.colonization++;
        },
    },
    {
        id: 4,
        name: "杜充降金",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "消灭1个宋国部队，征募1个签军〔不能消灭皇帝或将领所在区域的部队〕。若【宗泽】不在场，则效果翻倍。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：消灭1个宋国部队，征募1个签军〔不能消灭皇帝或将领所在区域的部队〕。若【宗泽】不在场，则效果翻倍。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 5,
        name: "金太宗",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在补充阶段开始时可以使用1行动力征募。在发展阶段提供额外1发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在补充阶段开始时可以使用1行动力征募。在发展阶段提供额外1发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("金太宗"),
    },
    {
        id: 6,
        name: "苗刘兵变",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【建炎南渡】发生后",
        combat: false,
        effectText: "宋国选择以下一项执行：弃掉1张手牌，并移动1个和宋国皇帝相邻的军团到宋国皇帝所在区域；或者宋国失去皇帝。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【建炎南渡】发生后 效果：宋国选择以下一项执行：弃掉1张手牌，并移动1个和宋国皇帝相邻的军团到宋国皇帝所在区域；或者宋国失去皇帝。",
        pre: (G, ctx) => G.song.activeEvents.includes("建炎南渡"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 7,
        name: "渡河！渡河！渡河！",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "第2回合开始之后",
        combat: false,
        effectText: "移除 宗泽",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：第2回合开始之后 效果：移除 宗泽",
        pre: (G, ctx) => G.turnMarker >= 2,
        event: (G, ctx, arg) => removeGeneral(G, ctx, G.song, "宗泽"),
    },
    {
        id: 8,
        name: "追亡逐北",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "移除西辽。",
        unlock: "",
        block: "【耶律大石】",
        ban: "",
        fullDesc: " 效果：移除西辽。 禁止：【耶律大石】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.otherCountries["西辽"].exist = false,
    },
    {
        id: 9,
        name: "济南知府刘豫",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在历城消灭灭全部宋国部队，放置2个签军。",
        unlock: "【建立大齐】",
        block: "",
        ban: "",
        fullDesc: " 效果：在历城消灭灭全部宋国部队，放置2个签军。 解锁：【建立大齐】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            let t = songTroopInCity(12);
            removeTroop(G, ctx, t);
            if (t.general.length > 0) {
                G.song.pendingGeneralSave = t.general;
                ctx.events.setActivePlayers({others: null})
            }
        },
    },
    {
        id: 10,
        name: "猛安谋克",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "使用3行动力征募。若降低1级殖民能力，则可以使用6行动力征募，且无视内政等级限制。不能征募签军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：使用3行动力征募。若降低1级殖民能力，则可以使用6行动力征募，且无视内政等级限制。不能征募签军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (arg.colonizeLevelDown) {
                G.opForRecruitAndMarch = 6;
            } else {
                G.opForRecruitAndMarch = 3
            }
            ctx.events.setStage('recruit')
        },
    },
    {
        id: 11,
        name: "辽国旧部",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "金国每控制西京路、北京路、燕京路或东京路中的1个，就可以使用1行动力征募〔不受内政等级限制",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：金国每控制西京路、北京路、燕京路或东京路中的1个，就可以使用1行动力征募〔不受内政等级限制",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 12,
        name: "六甲神兵",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个被围困的城市发动进攻，在远程阶段城防的作用改为：攻城方增加等于城防的战斗力，守城方减少等于城防的战斗力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个被围困的城市发动进攻，在远程阶段城防的作用改为：攻城方增加等于城防的战斗力，守城方减少等于城防的战斗力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 13,
        name: "金兵来了",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【靖康之变】发生后且金国军团与宋国皇帝处在相邻区域",
        combat: false,
        effectText: "禁止拥立。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后且金国军团与宋国皇帝处在相邻区域 效果：禁止拥立。",
        pre: (G, ctx) => {
            if (G.jinn.activeEvents.includes("靖康之变") && G.song.emperor.exist) {
                let r = getRegionById(getCityByID(G.song.emperor.city).region);
                let adj = r.adjacentThroughMountainPass.concat(
                    r.waterAdjacent,
                    r.landAdjacent,
                    r.mountainAdjacent
                )
                return adj.some(region => jinnTroopInRegion(region) !== false);
            }
        },
        event: (G, ctx, arg) => G.jinn.activeEvents.push("金兵来了"),

    },
    {
        id: 14,
        name: "西军内斗",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "吴玠或吴璘未参战，且战斗在陕西六路或川峡四路",
        combat: true,
        effectText: "战斗牌宋国战斗骰点数减1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：吴玠或吴璘未参战，且战斗在陕西六路或川峡四路 效果：战斗牌宋国战斗骰点数减1。",
        pre: (G, ctx) => {
            let t = G.combatInfo.song.troop;
            if (t.general.includes("吴玠") || t.general.includes("吴璘")) {
                return false;
            } else {
                // TODO mountain pass
            }
        },
        event: (G, ctx, arg) => G,
    },
    {
        id: 15,
        name: "河面封冻",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "冬季",
        combat: false,
        effectText: "使用1行动力进军，不受河流边界限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：冬季 效果：使用1行动力进军，不受河流边界限制。",
        pre: (G, ctx) => G.turnMarker === 2 || G.roundMarker === 6,
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("河面封冻")
            ctx.events.setStage("march")
        },
    },
    {
        id: 16,
        name: "掠夺",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季或秋季",
        combat: false,
        effectText: "使用1行动力进军，不受补给限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季或秋季 效果：使用1行动力进军，不受补给限制。",
        pre: (G, ctx) => G.roundMarker === 4 || G.roundMarker === 5 || G.roundMarker === 8 || G.roundMarker === 1,
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("掠夺")
            ctx.events.setStage("march");
        },
    },
    {
        id: 17,
        name: "张赵之争",
        op: 4,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "放置1个在场的宋国将领到预备兵区或者宋国内政等级降低1级。【莫须有】结算时，金国内政等级视为提升1级的状态。",
        unlock: "【秦桧独相】【淮西军变】",
        block: "【任用赵鼎张浚】",
        ban: "",
        fullDesc: " 效果：放置1个在场的宋国将领到预备兵区或者宋国内政等级降低1级。【莫须有】结算时，金国内政等级视为提升1级的状态。 解锁：【秦桧独相】【淮西军变】 禁止：【任用赵鼎张浚】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 18,
        name: "建立大齐",
        op: 4,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【济南知府刘豫】发生后",
        combat: false,
        effectText: "在3个金国控制的路，放置齐控制标志，齐控制的城市视为完成了殖民。金国获得齐军征募许可，齐军在任何结算时都同时视为签军。若金国军事等级不小于5 ,签军获得远程属性。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【济南知府刘豫】发生后 效果：在3个金国控制的路，放置齐控制标志，齐控制的城市视为完成了殖民。金国获得齐军征募许可，齐军在任何结算时都同时视为签军。若金国军事等级不小于5 ,签军获得远程属性。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 19,
        name: "兀朮登场",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除斡离不。在1个金国控制的区域放置兀术。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除斡离不。在1个金国控制的区域放置兀术。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "斡离不")
            // TODO
        },
    },
    {
        id: 20,
        name: "银术可登场",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个金国控制的区域放置银术可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个金国控制的区域放置银术可。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 21,
        name: "秦桧独相",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【张赵之争】发生后",
        combat: false,
        effectText: "宋国每回合开始时腐败值加1。【莫须有】结算时，金国内政等级视为再提升1级的状态。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【张赵之争】发生后 效果：宋国每回合开始时腐败值加1。【莫须有】结算时，金国内政等级视为再提升1级的状态。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("张赵之争"),
        event: (G, ctx, arg) => G.jinn.activeEvents.push("秦桧独相"),
    },
    {
        id: 22,
        name: "重点进攻",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移动1个金国军团到所在路内或相邻路内1座没有被围困的金国城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移动1个金国军团到所在路内或相邻路内1座没有被围困的金国城市。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 23,
        name: "三年之约",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季或秋季",
        combat: false,
        effectText: "在陕西六路，使用本卡牌的行动力对任意没有宋国将领的军团执行进军。移除娄室。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季或秋季 效果：在陕西六路，使用本卡牌的行动力对任意没有宋国将领的军团执行进军。移除娄室。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 24,
        name: "淮西军变",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【张赵之争】发生后",
        combat: false,
        effectText: "在准南两路，消灭2个部队。征募2个步兵和1个战船（不受内政等级限制〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【张赵之争】发生后 效果：在准南两路，消灭2个部队。征募2个步兵和1个战船（不受内政等级限制〕。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("张赵之争"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 25,
        name: "烽火扬州路",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国控制杨州地区",
        combat: false,
        effectText: "与另1张牌一起打出，行动点数合并计算。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国控制杨州地区 效果：与另1张牌一起打出，行动点数合并计算。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 26,
        name: "搜山检海",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝被围困",
        combat: false,
        effectText: "宋国失去皇帝。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝被围困 效果：宋国失去皇帝。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.song.emperor.exist = false;
            if (G.song.policy > -3) G.song.policy--;
        },
    },
    {
        id: 27,
        name: "孤注一掷",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "齐只控制1个路",
        combat: false,
        effectText: "降低1级殖民能力，在所有齐控制的城市，各放置1个签军和1个拐子马。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：齐只控制1个路 效果：降低1级殖民能力，在所有齐控制的城市，各放置1个签军和1个拐子马。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 28,
        name: "唃厮啰入侵",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若吐蕃中立，在川峡四路，放置1个步兵；若吐蕃是金国的盟国，则效果翻倍。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若吐蕃中立，在川峡四路，放置1个步兵；若吐蕃是金国的盟国，则效果翻倍。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 29,
        name: "天眷新政",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【金太宗驾崩】发生后",
        combat: false,
        effectText: "弃掉数是最多等于内政等级的手牌，然后从金国牌库摸取相等数畺的牌。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【金太宗驾崩】发生后 效果：弃掉数是最多等于内政等级的手牌，然后从金国牌库摸取相等数畺的牌。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("金太宗驾崩"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 30,
        name: "不见来使",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "禁止宋国对高丽执行外交。若高丽是金国的盟国，则在发展阶段额外提供1发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：禁止宋国对高丽执行外交。若高丽是金国的盟国，则在发展阶段额外提供1发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("不见来使"),
    },
    {
        id: 31,
        name: "曲端之死",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "金国控制河东路或陕西六路",
        combat: false,
        effectText: "在陕西六路，消灭2个部队。",
        unlock: "",
        block: "【西军曲端】",
        ban: "【西军曲端】",
        fullDesc: "前置条件：金国控制河东路或陕西六路 效果：在陕西六路，消灭2个部队。 禁止：【西军曲端】 撤销：【西军曲端】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("曲端之死"),
    },
    {
        id: 32,
        name: "火攻",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "兀术在场",
        combat: true,
        effectText: "战斗牌消灭1个参战的宋国战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：兀术在场 效果：战斗牌消灭1个参战的宋国战船。",
        pre: (G, ctx) => G.jinn.generals["兀术"].present,
        event: (G, ctx, arg) => G,
    },
    {
        id: 33,
        name: "江淮流宼",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个宋国控制的路内，没有宋国军团的区域，放置1个签军和1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个宋国控制的路内，没有宋国军团的区域，放置1个签军和1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 34,
        name: "胡服乡兵",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "有签军参战",
        combat: true,
        effectText: "战斗牌消灭1个参战的宋国步兵或弓兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：有签军参战 效果：战斗牌消灭1个参战的宋国步兵或弓兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 35,
        name: "李成",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个有签军的军团内，放置2个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个有签军的军团内，放置2个步兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 36,
        name: "徐州冶铁",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "内政等级不低于5且控制京东两路",
        combat: false,
        effectText: "铁浮屠征募消耗变为1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：内政等级不低于5且控制京东两路 效果：铁浮屠征募消耗变为1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.jinn.recruitCost[2] = 1;
            G.jinn.activeEvents.push("徐州冶铁")
        },
    },
    {
        id: 37,
        name: "孔彦舟",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个有签军的军团内，放置1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个有签军的军团内，放置1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 38,
        name: "杀马为粮",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "替换1个金国骑行部队为步兵，这个步兵所在的军团立即进军，不受补给限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：替换1个金国骑行部队为步兵，这个步兵所在的军团立即进军，不受补给限制。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 39,
        name: "徽宗病逝",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若【靖康之变】已经发生，免费和议。若【靖康之变】没有发生，宋国随机弃掉1张手牌",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若【靖康之变】已经发生，免费和议。若【靖康之变】没有发生，宋国随机弃掉1张手牌",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 40,
        name: "南人归南 北人归北",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "用此牌发展，提供发展力等于实时殖民能力的2倍",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：用此牌发展，提供发展力等于实时殖民能力的2倍",
        pre: (G, ctx) => false,
        event: (G, ctx, arg) => G,
    },
    {
        id: 41,
        name: "莫須有",
        op: 4,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国内政等级不低于7",
        combat: false,
        effectText: "降低2级政策倾向，消灭宋国总共4个部队。若此时政策倾向为和议，则移除岳飞。否则，放置岳飞到预备兵区。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国内政等级不低于7 效果：降低2级政策倾向，消灭宋国总共4个部队。若此时政策倾向为和议，则移除岳飞。否则，放置岳飞到预备兵区。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 42,
        name: "奔睹登场",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个金国控制的区域放置奔睹。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个金国控制的区域放置奔睹。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 43,
        name: "天眷政变",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "金国军事等级不低于5",
        combat: false,
        effectText: "提升金国1级军事等级，本回合作战计划替换为【吴山立马】。",
        unlock: "",
        block: "【完颜昌主和】",
        ban: "",
        fullDesc: "前置条件：金国军事等级不低于5 效果：提升金国1级军事等级，本回合作战计划替换为【吴山立马】。 禁止：【完颜昌主和】",
        pre: (G, ctx) => G.jinn.military >= 5,
        event: (G, ctx, arg) => G,
    },
    {
        id: 44,
        name: "十二道金牌",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "使用该卡牌的行动点数，对宋国军团执行进军，不能触发战斗，不能移动到缺乏的区域。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：使用该卡牌的行动点数，对宋国军团执行进军，不能触发战斗，不能移动到缺乏的区域。",
        pre: (G, ctx) => getPolicy(G,ctx) < 0,
        event: (G, ctx, arg) => G,
    },
    {
        id: 45,
        name: "败盟南下",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "降低1级政策倾向，使用这张牌的行动力执行征募和进军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：降低1级政策倾向，使用这张牌的行动力执行征募和进军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) =>  {
            if(G.song.policy > -3) G.song.policy --;
            G.opForRecruitAndMarch = 3;
            ctx.events.setStage('recruitOrMarch')
        },
    },
    {
        id: 46,
        name: "解除兵权",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "若宋国皇帝在场，则将韩世忠移动到皇帝所在区域，韩世忠之后只能随宋国皇帝移动。否则，移除韩世忠。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：若宋国皇帝在场，则将韩世忠移动到皇帝所在区域，韩世忠之后只能随宋国皇帝移动。否则，移除韩世忠。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 47,
        name: "臣构言",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若政策倾向为和议，提升1级殖民能力。若政策倾向为主战或中立，降低1级政策倾向。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若政策倾向为和议，提升1级殖民能力。若政策倾向为主战或中立，降低1级政策倾向。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if(getPolicy(G,ctx,)<0){
                G.jinn.colonization ++;
            }else{
                if(G.song.policy>-3)G.song.policy--;
            }
        },
    },
    {
        id: 48,
        name: "吴玠病逝",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除吴玠",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除吴玠",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => removeGeneral(G,ctx,G.jinn,"吴玠"),
    },
    {
        id: 49,
        name: "钱眼将军张俊",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "宋国腐败值加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：宋国腐败值加1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.song.corruption++,
    },
    {
        id: 50,
        name: "疑兵",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "奔睹在场，且金国守城",
        combat: true,
        effectText: "战斗牌先于任何战斗卡结算，宋国军团立即撤退，全部战斗结算结束。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：奔睹在场，且金国守城 效果：战斗牌先于任何战斗卡结算，宋国军团立即撤退，全部战斗结算结束。",
        pre: (G, ctx) => G.jinn.generals["奔睹"].present && G.combatInfo.isSiege && G.combatInfo.song.isAttacker,
        event: (G, ctx, arg) => G,
    },
]
