export const provinces = [{
    id: 0,
    name: "",
    adjacent: [],
    capital: [],
    otherCities: [],
    adjacentForeignCountries: [],
},{
    id: 1,
    name: "西京路",
    adjacent: [2, 4, 5],
    capital: [1],
    otherCities: [],
    adjacentForeignCountries: [],
},
    {
        id: 2,
        name: "北京路",
        adjacent: [1, 3, 4],
        capital: [2],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 3,
        name: "燕京路",
        adjacent: [2, 4],
        capital: [],
        otherCities: [4],
        adjacentForeignCountries: [],
    },
    {
        id: 4,
        name: "东京路",
        adjacent: [1, 2, 6],
        capital: [3],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 5,
        name: "河东路",
        adjacent: [1, 6, 8, 9, 10],
        capital: [5],
        otherCities: [6, 7],
        adjacentForeignCountries: [],
    },
    {
        id: 6,
        name: "河北两路",
        adjacent: [1, 4, 5, 7, 9, 10],
        capital: [11],
        otherCities: [8, 9, 10],
        adjacentForeignCountries: [],
    },
    {
        id: 7,
        name: "京东两路",
        adjacent: [6, 10, 11],
        capital: [14],
        otherCities: [12, 13],
        adjacentForeignCountries: [],
    },
    {
        id: 8,
        name: "陕西六路",
        adjacent: [5, 9, 12],
        capital: [17],
        otherCities: [15, 16],
        adjacentForeignCountries: [],
    },
    {
        id: 9,
        name: "京西两路",
        adjacent: [5, 6, 8, 10, 11, 12, 13],
        capital: [20],
        otherCities: [18, 19],
        adjacentForeignCountries: [],
    },
    {
        id: 10,
        name: "京畿路",
        adjacent: [6, 7, 9, 11],
        capital: [21],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 11,
        name: "淮南两路",
        adjacent: [7, 9, 10, 13, 14, 15],
        capital: [22],
        otherCities: [23],
        adjacentForeignCountries: [],
    },
    {
        id: 12,
        name: "川陕四路",
        adjacent: [8, 9, 13],
        capital: [25],
        otherCities: [24, 26],
        adjacentForeignCountries: [],
    },
    {
        id: 13,
        name: "荆湖两路",
        adjacent: [9, 11, 12, 14],
        capital: [27],
        otherCities: [28, 29],
        adjacentForeignCountries: [],
    },
    {
        id: 14,
        name: "江南两路",
        adjacent: [11, 13, 15, 16],
        capital: [30],
        otherCities: [31],
        adjacentForeignCountries: [],
    },
    {
        id: 15,
        name: "两浙路",
        adjacent: [11, 14, 16],
        capital: [32, 34],
        otherCities: [33],
        adjacentForeignCountries: [],
    },
    {
        id: 16,
        name: "福建路",
        adjacent: [14, 15],
        capital: [35],
        otherCities: [],
        adjacentForeignCountries: [],
    },]
