import {drawCardForSong, getPolicy, getSongBackupCount, removeGeneral} from "../auto/util";
import {getCityByID} from "./cities";

export const songCards = [
    {
        id: 0,
        name: "",
        op: 0,
        desc: "",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    }, {
        id: 1,
        name: "建炎南渡",
        op: 4,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国未控制开封",
        combat: false,
        effectText: "在两浙路或江南两路免费拥立。宋国获得1国力禁止金国以事件方式在两浙路放置部队。",
        unlock: "【苗刘兵变】",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国未控制开封 效果：在两浙路或江南两路免费拥立。宋国获得1国力禁止金国以事件方式在两浙路放置部队。 解锁：【苗刘兵变】",
        pre: (G, ctx) => !G.song.cities.includes(21),
        event: (G, ctx, arg) => {
            G.song.activeEvents.push('建炎南渡')
        },
    },
    {
        id: 2,
        name: "李纲",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "回合",
        precondition: "第7回合前",
        combat: false,
        effectText: "腐败值减1。本回合余下的时间内，政策倾向视为提升2级的状态（最高为主战3）。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：第7回合前 效果：腐败值减1。本回合余下的时间内，政策倾向视为提升2级的状态（最高为主战3）。",
        pre: (G, ctx) => {
            return G.turnMarker < 7
        },
        event: (G, ctx, arg) => {
            G.song.corruption--;
            G.song.activeEvents.push('李纲')
        },
    },
    {
        id: 3,
        name: "靖康学生运动",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "腐败值变为0 ,每因此减少1点腐败值就提升1级政策倾向。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：腐败值变为0 ,每因此减少1点腐败值就提升1级政策倾向。",
        pre: (G, ctx) => getPolicy(G, ctx) < 1,
        event: (G, ctx, arg) => {
            G.song.policy += G.song.corruption;
            G.song.corruption = 0;
        },
    },
    {
        id: 4,
        name: "西军曲端",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "【三年之约】作为事件打出时行动点数减1。每当回合结束阶段时，宋国在陕西六路放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：【三年之约】作为事件打出时行动点数减1。每当回合结束阶段时，宋国在陕西六路放置1个步兵。",
        pre: (G, ctx) => !G.jinn.activeEvents.includes("曲端之死"),
        event: (G, ctx, arg) => {
            G.song.activeEvents.push("西军曲端")
        },
    },
    {
        id: 5,
        name: "天下兵马大元帅",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移动1个宋国军团到所在路内或相邻路内1座没有被围困的宋国城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移动1个宋国军团到所在路内或相邻路内1座没有被围困的宋国城市。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            // TODO component in player hand
            arg.troop.city = arg.city;
            arg.troop.region = getCityByID(arg.city).region;
        },
    },
    {
        id: 6,
        name: "霹雳炮",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个宋国控制的城市，放置1个霹雳炮。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个宋国控制的城市，放置1个霹雳炮。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            let hasExistingTroop = false;
            for (let troop of G.song.troops) {
                if (troop.city === arg.dst) {
                    hasExistingTroop = true;
                    troop.units[4] += 1;
                }
            }
            if (!hasExistingTroop) {
                G.song.troops.push({
                    units: [0, 0, 0, 0, 1, 0],
                    city: arg.dst,
                })
            }
        },
    },
    {
        id: 7,
        name: "一盆凉水",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季",
        combat: false,
        effectText: "移除斡离不。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季 效果：移除斡离不。",
        pre: (G, ctx) => G.roundMarker === 4 || G.roundMarker === 8,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "斡离不");
        },
    },
    {
        id: 8,
        name: "张邦昌还政",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【靖康之变】发生后",
        combat: false,
        effectText: "金国在开封的军团移动到大同府或大定府，宋国在开封放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后 效果：金国在开封的军团移动到大同府或大定府，宋国在开封放置1个步兵。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("靖康之变"),
        event: (G, ctx, arg) => {
            for (let troop of G.jinn.troops) {
                if (troop.city === 21) {
                    troop.city = arg.dst;
                    troop.region = getCityByID(arg.dst).region;
                }
                let troopInKaiFeng = false;
                for (let troop of G.song.troops) {
                    if (troop.city === 21) {
                        troopInKaiFeng = true;
                        troop.units[0]++;
                    }
                }
                if (!troopInKaiFeng) {
                    G.song.troops.push({
                        units: [1, 0, 0, 0, 0, 0],
                        city: 21,
                        region: 43,
                    })
                }
            }
        },
    },
    {
        id: 9,
        name: "耶律大石",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "西辽成为宋国的盟国。若西辽已经是宋国的盟国，消灭金国1个部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：西辽成为宋国的盟国。若西辽已经是宋国的盟国，消灭金国1个部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (G.otherCountries["西辽"].state === 'song') {
                G.eventActionInfo = {
                    type: "kill-X-Units",
                    arg: 1,
                }
                ctx.events.setStage('killUnit');
            } else {
                G.otherCountries["西辽"].state = 'song';
            }
        },
    },
    {
        id: 10,
        name: "李彦仙",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1座被围困的城市放置1个步兵，或者消灭围城军团的1个部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1座被围困的城市放置1个步兵，或者消灭围城军团的1个部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            ctx.events.setStage("LiYanXian");
        },
    },
    {
        id: 11,
        name: "勤王诏令",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "宋国按照补充规则，在宋国控制且殖民难度大于金国殖民能力的城市，放置预备兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：宋国按照补充规则，在宋国控制且殖民难度大于金国殖民能力的城市，放置预备兵。",
        pre: (G, ctx) => G.song.emperor.exist,
        event: (G, ctx, arg) => G,
    },
    {
        id: 12,
        name: "战车",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宗泽在场",
        combat: true,
        effectText: "战斗牌在平原，宋国每个步兵战斗力加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宗泽在场 效果：战斗牌在平原，宋国每个步兵战斗力加1。",
        pre: (G, ctx) => G.song.generals["宗泽"].present,
        event: (G, ctx, arg) => G,
    },
    {
        id: 13,
        name: "红巾军",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "金国每控制1个尚未殖民的城市，宋国就在隆德府放置1个步兵〔上限为宋国军事等级〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：金国每控制1个尚未殖民的城市，宋国就在隆德府放置1个步兵〔上限为宋国军事等级〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 14,
        name: "大理矮脚马",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若大理中立，则征募1个骑兵。若大理是宋国的盟国，则效果翻倍且不受内政等级限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若大理中立，则征募1个骑兵。若大理是宋国的盟国，则效果翻倍且不受内政等级限制。",
        pre: (G, ctx) => G.otherCountries["大理"].state !== 'jinn',
        event: (G, ctx, arg) => {
            if (G.otherCountries["大理"].state === 'song') {
                if(getSongBackupCount(G,ctx,) < G.song.civil){
                    G.song.reserveBank[2] -= 1;
                    G.song.supplementBank[2] += 1;
                }
            } else {
                let count;
                if (G.song.reserveBank[2] < 2) {
                    count = G.song.reserveBank[2];
                }
                G.song.reserveBank[2] -= count;
                G.song.supplementBank[2] += count;
            }
        },
    },
    {
        id: 15,
        name: "八字军",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在河北两路的1个区域，放置2个步兵。【刘錡】伤害加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在河北两路的1个区域，放置2个步兵。【刘錡】伤害加1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.song.activeEvents.push("八字军");

        },
    },
    {
        id: 16,
        name: "赵榛",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【靖康之变】发生后",
        combat: false,
        effectText: "在1个未完成殖民的金国城市，放置2个步兵，这个城市所在的路结算控制权。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后 效果：在1个未完成殖民的金国城市，放置2个步兵，这个城市所在的路结算控制权。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("靖康之变"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 17,
        name: "金太宗驾崩",
        op: 4,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "第5回合开始之后",
        combat: false,
        effectText: "移除粘罕，选择金国内政等级、军事等级或殖民能力降低1级。",
        unlock: "【完颜昌主和】【天眷新政】",
        block: "【金太宗】",
        ban: "【金太宗】",
        fullDesc: "前置条件：第5回合开始之后 效果：移除粘罕，选择金国内政等级、军事等级或殖民能力降低1级。 解锁：【完颜昌主和】【天眷新政】 禁止：【金太宗】 撤销：【金太宗】",
        pre: (G, ctx) => G.turnMarker > 4,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "粘罕");
            if(arg.target === 'civil' || arg.target==='military' || arg.target==='colonization'){
                G.jinn[arg.target] --;
            }

        },
    },
    {
        id: 18,
        name: "废黜伪齐",
        op: 4,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【建立大齐】发生后",
        combat: false,
        effectText: "移除1个齐状态标志物，结算这个路的控制权，消灭2个齐军。若此时齐控制的城市不多于4个，则金国失去齐军征募许可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【建立大齐】发生后 效果：移除1个齐状态标志物，结算这个路的控制权，消灭2个齐军。若此时齐控制的城市不多于4个，则金国失去齐军征募许可。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("建立大齐"),
        event: (G, ctx, arg) => {

        },
    },
    {
        id: 19,
        name: "岳飞登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国军事等级不低于4",
        combat: false,
        effectText: "移除宗泽，在准南两路或荆湖两路放置岳飞。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于4 效果：移除宗泽，在准南两路或荆湖两路放置岳飞。",
        pre: (G, ctx) => G.song.military >= 4,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.song, "宗泽");

        },

    },
    {
        id: 20,
        name: "吴玠登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在陕西六路或川峡四路内的1个城市放置吴玠。若这座城市没有部队，则放置2个弓兵到该城市",
        unlock: "",
        block: "",
        ban: "【西军曲端】",
        fullDesc: " 效果：在陕西六路或川峡四路内的1个城市放置吴玠。若这座城市没有部队，则放置2个弓兵到该城市 撤销：【西军曲端】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 21,
        name: "韩世忠登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "在宋国皇帝所在的区域放置韩世忠。若相邻区域有金国部队，则放置2个步兵到该城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：在宋国皇帝所在的区域放置韩世忠。若相邻区域有金国部队，则放置2个步兵到该城市。",
        pre: (G, ctx) => G.song.emperor.exist,
        event: (G, ctx, arg) => G,
    },
    {
        id: 22,
        name: "无路可退",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国国力不大于7时",
        combat: false,
        effectText: "每当金国失去1点国力，宋国政策倾向提升1级。若事件发生时宋国国力不大于6 ,则立即在3个宋国控制的核心城市各放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国国力不大于7时 效果：每当金国失去1点国力，宋国政策倾向提升1级。若事件发生时宋国国力不大于6 ,则立即在3个宋国控制的核心城市各放置1个步兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 23,
        name: "完顔昌主和",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【金太宗驾崩】发生后",
        combat: false,
        effectText: "降低金国1级军事等级。若兀术在场，则放置到预备兵区。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【金太宗驾崩】发生后 效果：降低金国1级军事等级。若兀术在场，则放置到预备兵区。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 24,
        name: "向海上发展",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国内政等级不低于5",
        combat: false,
        effectText: "福建路提供1国力。宋国可以从平江府向高丽进行外交。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国内政等级不低于5 效果：福建路提供1国力。宋国可以从平江府向高丽进行外交。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 25,
        name: "背嵬军",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "征募2个背嵬军。若岳飞在场，则可以在岳飞所在区域，直接放置这2个背嵬军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：征募2个背嵬军。若岳飞在场，则可以在岳飞所在区域，直接放置这2个背嵬军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 26,
        name: "伪齐良马",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "齐每控制1个路，宋国就征募1个骑兵（不受内政等级限制〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：齐每控制1个路，宋国就征募1个骑兵（不受内政等级限制〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 27,
        name: "任用赵鼎 张浚",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "腐败值减1。若腐败值已经为0 ,则提升1级政策倾向。发展阶段时，提供4点发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：腐败值减1。若腐败值已经为0 ,则提升1级政策倾向。发展阶段时，提供4点发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 28,
        name: "锁江困敌",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "征募2个战船。若韩世忠在场，则可以在韩世忠所在区域，直接放置这2个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：征募2个战船。若韩世忠在场，则可以在韩世忠所在区域，直接放置这2个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 29,
        name: "招降",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌每消灭或击溃1个签军，就征募1个步兵，不受内政等级限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌每消灭或击溃1个签军，就征募1个步兵，不受内政等级限制。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 30,
        name: "浮海逃生",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "当宋国失去皇帝时，可以移除这张牌，移动宋国皇帝到任意宋国控制的城市。",
        unlock: "",
        block: "【搜山检海】",
        ban: "",
        fullDesc: " 效果：当宋国失去皇帝时，可以移除这张牌，移动宋国皇帝到任意宋国控制的城市。 禁止：【搜山检海】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 31,
        name: "改进神臂弓",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国军事等级不低于5",
        combat: false,
        effectText: "宋国弓兵在全部地形战斗力变为2 ,征募消变为2。",
        unlock: "",
        block: "【普及重步兵】",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于5 效果：宋国弓兵在全部地形战斗力变为2 ,征募消变为2。 禁止：【普及重步兵】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 32,
        name: "普及重步兵",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国军事等级不低于5",
        combat: false,
        effectText: "宋国步兵耐久度加1。",
        unlock: "",
        block: "【改进神臂弓】",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于5 效果：宋国步兵耐久度加1。 禁止：【改进神臂弓】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 33,
        name: "杨沂中",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在宋国皇帝所在的区域放置1个步兵和1个弓兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在宋国皇帝所在的区域放置1个步兵和1个弓兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 34,
        name: "金夏边境冲突",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若西夏是宋国的盟国，则消灭总共2耐久的部队若西夏中立，则消灭总共1耐久的部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若西夏是宋国的盟国，则消灭总共2耐久的部队若西夏中立，则消灭总共1耐久的部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 35,
        name: "水浒赛",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在泰州地区放置1个战船，在准南两路消灭1个金国部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在泰州地区放置1个战船，在准南两路消灭1个金国部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 36,
        name: "岳家军",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "岳飞在场",
        combat: true,
        effectText: "战斗牌参战军团中视为增加1个岳飞。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场 效果：战斗牌参战军团中视为增加1个岳飞。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 37,
        name: "驻队矢",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌宋国远程部队在远程阶段和交锋阶段优先结算。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌宋国远程部队在远程阶段和交锋阶段优先结算。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 38,
        name: "王庶",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【曲端之死】发生后",
        combat: false,
        effectText: "在陕西六路和川峡四路每个宋国控制的城市，各放置1个【步兵】〔上限为宋国军事等级〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【曲端之死】发生后 效果：在陕西六路和川峡四路每个宋国控制的城市，各放置1个【步兵】〔上限为宋国军事等级〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 39,
        name: "《守城录》",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国军团在城墙时",
        combat: true,
        effectText: "战斗牌金国战斗骰点数减1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国军团在城墙时 效果：战斗牌金国战斗骰点数减1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 40,
        name: "刘光世",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "腐败值加1。使用这张牌的行动力执行征募和进军，若没有触发任何战斗，则用此牌执行发展。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：腐败值加1。使用这张牌的行动力执行征募和进军，若没有触发任何战斗，则用此牌执行发展。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 41,
        name: "岳帅之来此间震恐",
        op: 4,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "回合",
        precondition: "岳飞在场且宋国军事等级不低于6",
        combat: false,
        effectText: "宋国作战计划替换为【还我河山】。本回合内宋国所有战斗骰点数加1。当岳飞被移除时，此事件被撤销。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场且宋国军事等级不低于6 效果：宋国作战计划替换为【还我河山】。本回合内宋国所有战斗骰点数加1。当岳飞被移除时，此事件被撤销。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 42,
        name: "李显忠登场",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "西夏向金国方向调整1级。在1个宋国控制的区域放置李显忠和2个骑兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：西夏向金国方向调整1级。在1个宋国控制的区域放置李显忠和2个骑兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 43,
        name: "刘錡",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "掷骰1次，对1个围城军团造成等于掷骰点数的伤害。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：掷骰1次，对1个围城军团造成等于掷骰点数的伤害。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 44,
        name: "吴璘登场",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在陕西六路或川峡四路放置吴璘。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在陕西六路或川峡四路放置吴璘。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 45,
        name: "梁兴渡河",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "岳飞在场",
        combat: false,
        effectText: "降低金国1级殖民能力，用此牌执行发展。发展阶段，此牌提供发展力等于金国占领但没有完成殖民的城市数量。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场 效果：降低金国1级殖民能力，用此牌执行发展。发展阶段，此牌提供发展力等于金国占领但没有完成殖民的城市数量。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 46,
        name: "定都临安",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "移动宋国皇帝到钱塘，用此牌执行派遣。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：移动宋国皇帝到钱塘，用此牌执行派遣。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 47,
        name: "告老迁乡",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除银术可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除银术可。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => removeGeneral(G, ctx, G.jinn, "银术可"),
    },
    {
        id: 48,
        name: "北谒宋陵",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国控制洛阳",
        combat: false,
        effectText: "用此牌执行发展，宋国摸1张牌。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国控制洛阳 效果：用此牌执行发展，宋国摸1张牌。",
        pre: (G, ctx) => G.song.cities.includes(18),
        event: (G, ctx, arg) => {
            G.song.developCards.push(48);
            drawCardForSong(G, ctx);
        },
    },
    {
        id: 49,
        name: "燕京以南 号令不行",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国控制析津",
        combat: false,
        effectText: "放在宋国完成的作战计划堆最上面。绍兴和议时，宋国额外获得1胜利分数。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国控制析津 效果：放在宋国完成的作战计划堆最上面。绍兴和议时，宋国额外获得1胜利分数。",
        pre: (G, ctx) => G.song.cities.includes(4),
        event: (G, ctx, arg) => G.song.activeEvents.push("燕京以南 号令不行"),
    },
    {
        id: 50,
        name: "李宝",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌 在宋国参战军团，放置1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌 在宋国参战军团，放置1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
]
